# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077b6e22618812a335d91d224c5737207b075c6ca0a446d9133d367932539cc55e357ac5fb3129105555f6ba8d3d2e4fdd0a7330c4a7b5f8b9940a3d53c4887a

test:
  secret_key_base: 5533566ef9d918031224ddc4cbd9540cdc232abf73eea9694ad623dd601c7ea3e94bd0d52934fec8f68dcf00122b4283b85324da1ec5b3f22b63a5890df6796c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
